# Configuration file for TAC temporal alignment for control.

epochs: 200
lr: 0.005
batch_size : 10
nb_datapoints: -1 # number of datapoints from the dataset
plot: False # plot a few of the segmentations.
units : [200,200,50] # units in the architecture
architecture: bi-recurrent # architecture for policy or CTC
algorithm: ctc # algorithm CTC,TAC or STAC
mlp_complex: True # use an additional MLP on top of RNNs when doing STAC or TAC
entropy_reg: 0. # Regularise the classifiers. Not useful for toy settings.
discrete: False # Action space discrete or not
test_size: 0
gpu: False
image: False
action_noise: 0.00 # Action noise, useful when continuous and not toy
normalise_actions: True # States are always normalised, actions choose from here.
dropout: 0.8
dropout_decay: 1.001
gaps: False 
# use gaps in the CTC. Suggested: False

ctc-il: # parameters for the imitation network of the CTC-IL method. not used during TAC
 dropout: 1
 epochs: 200
 architecture: mlp
 units: [300,100,50]
 lr: 0.01


