action_noise: 0.0
algorithm: tac
architecture: mlp
batch_size: 6
ctc-il:
  architecture: mlp
  dropout: 1
  epochs: 300
  lr: 0.01
  units: [500, 100]
discrete: false
dropout: 0.7
dropout_decay: 1.001
entropy_reg: 0.0
epochs: 400
gaps: false
gpu: False
image: false
lr: 0.002
mlp_complex: true
nb_datapoints: 100
normalise_actions: true
plot: false
test_size: 0
units: [300,200,100]
