# Configuration file for TAC temporal alignment for control.
epochs: 200
lr: 0.001
batch_size : 3
nb_datapoints: 400 # number of datapoints from the dataset
test_size: 0
plot: False # plot a few of the segmentations.
units : [400,100] # units in the architecture
architecture: mlp # architecture for policy or CTC
algorithm: tac # algorithm CTC,TAC or STAC
mlp_complex: True # use an additional MLP on top of RNNs when doing STAC or TAC
entropy_reg: 0. # Regularise the classifiers. Not useful for toy settings.
image: conv_layers_10_5_3
gpu: 7
discrete: False # Action space discrete or not
action_noise: 0.00 # Action noise, useful when continuous and not toy
normalise_actions: True # States are always normalised, actions choose from here.
dropout: 0.7
dropout_decay: 1.0015
gaps: False # use gaps in the CTC. Suggested: False

ctc-il: # parameters for the imitation network of the CTC-IL method. not used during TAC
 dropout: 1
 epochs: 300
 architecture: mlp
 units: [500,100]
 lr: 0.01


